"""This code is meant to use the quickaccess files generated by the comprehensive_data_extraction_and_saving.py file. It uses said processed data to create a multitude of plots from them, including a Q1-Q2 plot for each HoQI, for each data proccessing type, a displacement timeseries for the HoQI's as well as the DOF, for all data proccessing types, ASD's for all of these and lastly the parameter timeseries plots. Please manually make a folder called Plot_files in the folder that this file is put in for the image plot .png's to be put into."""
import numpy as np
import matplotlib.pyplot as plt
from gwpy.timeseries import TimeSeries
from scipy.signal import find_peaks

## User selection
valid_input = True
print("You can decide which plots the program generates with the inputs below, afterwards it will run and output the ones you've selected as .png files. Please only answer with y for yes and n for no.")
while valid_input == True:
    all_data = input("Do you want to just have the program output all plots? Input y for yes and n for no besides here: ").lower()
    if all_data == "y" or all_data == "n": 
        valid_input = False
    else:
        print("Wrong input, please only input y for yes or n for no")

choices_dict = {"Q1_Q2_plots": True, "Timeseries_plots": True, "ASD_plots": True, "raw_data": True, "single_ellipse_data": True, "window_ellipse_data": True, "ellipse_params_timeseries": True, "velocity_data": True}
if all_data == "n":
    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the Q1 and Q2 plots? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["Q1_Q2_plots"] = False

    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the timeseries plots? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["Timeseries_plots"] = False

    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the ASD plots? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["ASD_plots"] = False

    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the raw data as .npy files? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["raw_data"] = False

    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the single ellipse fitted data as .npy files? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["single_ellipse_data"] = False

    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the windowed ellipse fitted data as .npy files? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["window_ellipse_data"] = False

    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the ellipse parameters timeseries as .npy files? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["ellipse_params_timeseries"] = False

    valid_input = True
    while valid_input == True:
        input_var = input("Do you want the program to output the velocity data plots? Input y for yes and n for no besides here: ").lower()
        if input_var == "y" or input_var == "n": 
            valid_input = False
        else:
            print("Wrong input, please only input y for yes or n for no")
    if input_var == "n": choices_dict["velocity_data"] = False

## Import relevant data
if choices_dict["raw_data"] == True:
    Q1_raw = np.load("End_Product_Code/raw_Q1_data.npy")
    Q2_raw = np.load("End_Product_Code/raw_Q2_data.npy")
    raw_HoQI_displacement = np.load("End_Product_Code/raw_HoQI_displacement_data.npy")
    raw_DOF_displacement = np.load("End_Product_Code/raw_DOF_displacement_data.npy")

if choices_dict["single_ellipse_data"] == True:
    Q1_single_ellipse = np.load("End_Product_Code/single_ellipse_Q1_data.npy")
    Q2_single_ellipse = np.load("End_Product_Code/single_ellipse_Q2_data.npy")
    single_ellipse_HoQI_displacement = np.load("End_Product_Code/single_ellipse_HoQI_displacement_data.npy")
    single_ellipse_DOF_displacement = np.load("End_Product_Code/single_ellipse_DOF_displacement_data.npy")

if choices_dict["window_ellipse_data"] == True:
    Q1_windowed_ellipse = np.load("End_Product_Code/windowed_ellipse_Q1_data.npy")
    Q2_windowed_ellipse = np.load("End_Product_Code/windowed_ellipse_Q2_data.npy")
    windowed_ellipse_HoQI_displacement = np.load("End_Product_Code/windowed_ellipse_HoQI_displacement_data.npy")
    windowed_ellipse_DOF_displacement = np.load("End_Product_Code/windowed_ellipse_DOF_displacement_data.npy")

## Q1-Q2 plots
if choices_dict["Q1_Q2_plots"] == True:
    names_list = ['1x', '2x', '3x', '1z', '2z', '3z']

    if choices_dict["raw_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                axes[i, j].set_ylabel('Q2')
                axes[i, j].set_xlabel('Q1')
                axes[i, j].plot(Q1_raw[i*3+j, :], Q2_raw[i*3+j, :], ',')
                axes[i, j].set_title(names_list[i*3+j])

        figure.tight_layout()
        figure.savefig("End_Product_Code/Plot_files/raw_data_Q1_Q2_plot.png")
        plt.close()

    if choices_dict["single_ellipse_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                axes[i, j].set_ylabel('Q2')
                axes[i, j].set_xlabel('Q1')
                axes[i, j].plot(Q1_single_ellipse[i*3+j, :], Q2_single_ellipse[i*3+j, :], ',r')
                axes[i, j].set_title(names_list[i*3+j])

        figure.tight_layout()
        figure.savefig("End_Product_Code/Plot_files/single_ellipse_data_Q1_Q2_plot.png")
        plt.close()

    if choices_dict["window_ellipse_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                axes[i, j].set_ylabel('Q2')
                axes[i, j].set_xlabel('Q1')
                axes[i, j].plot(Q1_windowed_ellipse[i*3+j, :], Q2_windowed_ellipse[i*3+j, :], ',g')
                axes[i, j].set_title(names_list[i*3+j])

        figure.tight_layout()
        figure.savefig("End_Product_Code/Plot_files/windowed_ellipse_data_Q1_Q2_plot.png")
        plt.close()

## Time-series
time = np.array(list(range(0, 3000000)))
names_list_DOF = ["x", "y", "z", "Rx", "Ry", "Rz"]

if choices_dict["Timeseries_plots"] == True:
    if choices_dict["raw_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                axes[i, j].set_ylabel('Displacement (um)')
                axes[i, j].set_xlabel('Time (ms)')
                axes[i, j].plot(time, raw_HoQI_displacement[i*3+j, :], ',')
                axes[i, j].set_title(names_list[i*3+j])

        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/raw_data_HoQI_displacement_plot.png")
        plt.close()

        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                if i == 0:
                    axes[i, j].set_ylabel('Displacement (um)')
                else:
                    axes[i, j].set_ylabel('Displacement (urad)')
                axes[i, j].set_xlabel('Time (ms)')
                axes[i, j].plot(time, raw_DOF_displacement[i*3+j, :], ',')
                axes[i, j].set_title(names_list_DOF[i*3+j])

        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/raw_data_DOF_displacement_plot.png")
        plt.close()

    if choices_dict["single_ellipse_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                axes[i, j].set_ylabel('Displacement (um)')
                axes[i, j].set_xlabel('Time (ms)')
                axes[i, j].plot(time, single_ellipse_HoQI_displacement[i*3+j, :], ',')
                axes[i, j].set_title(names_list[i*3+j])

        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/single_ellipse_data_HoQI_displacement_plot.png")
        plt.close()

        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                if i == 0:
                    axes[i, j].set_ylabel('Displacement (um)')
                else:
                    axes[i, j].set_ylabel('Displacement (urad)')
                axes[i, j].set_xlabel('Time (ms)')
                axes[i, j].plot(time, single_ellipse_DOF_displacement[i*3+j, :], ',')
                axes[i, j].set_title(names_list_DOF[i*3+j])

        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/single_ellipse_data_DOF_displacement_plot.png")
        plt.close()

    if choices_dict["window_ellipse_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                time = np.array(list(range(0, len(windowed_ellipse_HoQI_displacement[i*3+j, :]))))
                axes[i, j].set_ylabel('Displacement (um)')
                axes[i, j].set_xlabel('Time (ms)')
                axes[i, j].plot(time, windowed_ellipse_HoQI_displacement[i*3+j, :], ',')
                axes[i, j].set_title(names_list[i*3+j])

        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/windowed_ellipse_data_HoQI_displacement_plot.png")
        plt.close()

        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                if i == 0:
                    axes[i, j].set_ylabel('Displacement (um)')
                else:
                    axes[i, j].set_ylabel('Displacement (urad)')
                axes[i, j].set_xlabel('Time (ms)')
                axes[i, j].plot(time, windowed_ellipse_DOF_displacement[i*3+j, :], ',')
                axes[i, j].set_title(names_list_DOF[i*3+j])

        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/windowed_ellipse_data_DOF_displacement_plot.png")
        plt.close()
    
## ASD plots
segment_time_set = 1000
fs_set = 1000
window = 50

# the following functions plots the ASD's 
def get_asd(data, fs, segment_time):
    """
    get_asd(np.array, int, int) -> FrequencySeries
    Takes a list of displacements and outputs a spectral density diagram for said displacement. fs is the sample rate per second, and segment_time is the amount of seconds your dataset covers. 
    """
    data = np.asarray(data)
    data = data - np.mean(data) 
    ts = TimeSeries(data, sample_rate=fs)
    ASD = ts.asd(segment_time, overlap=segment_time/2) 
    return ASD

if choices_dict["ASD_plots"] == True:
    if choices_dict["raw_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd = get_asd(raw_HoQI_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_smooth = np.convolve(asd.value, np.ones(window)/window, mode='same')
                peaks, properties = find_peaks(np.log10(asd.value[asd.frequencies.value <= 100]), prominence=1.5)

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd.frequencies.value, asd_smooth)
                axes[i, j].plot(asd.frequencies.value[asd.frequencies.value <= 100][peaks], asd_smooth[asd.frequencies.value <= 100][peaks], "rv") # de rode markeringen moeten wel netjes op de 'gesmoothede' functie vallen
                for h, frequency in enumerate(asd.frequencies.value[asd.frequencies.value <= 100][peaks]):
                    prominence = properties["prominences"][h]
                    y_text = asd_smooth[asd.frequencies.value <= 100][peaks][h]
                    
                    axes[i, j].axvline(x=frequency, color='r', linestyle='--', linewidth=0.8, alpha=0.8)
                    axes[i, j].text(
                        frequency * 1.1,     
                        y_text,
                        f"f = {frequency:.2f} Hz",
                        fontsize=9,
                        color='r',
                        va='center',
                        rotation=0)
                axes[i, j].set_title(names_list[i*3+j])
                axes[i, j].grid(True, which="both")
                print("Peak frequencies (Hz) of the derivated data:", np.array2string(asd.frequencies.value[peaks], separator=", "))
                print("Prominences (strengths of the associated peaks):", np.array2string(properties["prominences"], separator=", "))
                print()


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/raw_data_HoQI_ASD_plot.png")
        plt.close()

        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd = get_asd(raw_DOF_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_smooth = np.convolve(asd.value, np.ones(window)/window, mode='same')
                peaks, properties = find_peaks(np.log10(asd.value[asd.frequencies.value <= 100]), prominence=1.5)

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd.frequencies.value, asd_smooth)
                axes[i, j].plot(asd.frequencies.value[asd.frequencies.value <= 100][peaks], asd_smooth[asd.frequencies.value <= 100][peaks], "rv") # de rode markeringen moeten wel netjes op de 'gesmoothede' functie vallen
                for h, frequency in enumerate(asd.frequencies.value[asd.frequencies.value <= 100][peaks]):
                    prominence = properties["prominences"][h]
                    y_text = asd_smooth[asd.frequencies.value <= 100][peaks][h]
                    
                    axes[i, j].axvline(x=frequency, color='r', linestyle='--', linewidth=0.8, alpha=0.8)
                    axes[i, j].text(
                        frequency * 1.1,     
                        y_text,
                        f"f = {frequency:.2f} Hz",
                        fontsize=9,
                        color='r',
                        va='center',
                        rotation=0)
                axes[i, j].set_title(names_list_DOF[i*3+j])
                axes[i, j].grid(True, which="both")
                print("Peak frequencies (Hz) of the derivated data:", np.array2string(asd.frequencies.value[peaks], separator=", "))
                print("Prominences (strengths of the associated peaks):", np.array2string(properties["prominences"], separator=", "))
                print()


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/raw_data_DOF_ASD_plot.png")
        plt.close()

    if choices_dict["single_ellipse_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd = get_asd(single_ellipse_HoQI_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_smooth = np.convolve(asd.value, np.ones(window)/window, mode='same')
                peaks, properties = find_peaks(np.log10(asd.value[asd.frequencies.value <= 100]), prominence=1.5)

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd.frequencies.value, asd_smooth)
                axes[i, j].plot(asd.frequencies.value[asd.frequencies.value <= 100][peaks], asd_smooth[asd.frequencies.value <= 100][peaks], "rv") # de rode markeringen moeten wel netjes op de 'gesmoothede' functie vallen
                for h, frequency in enumerate(asd.frequencies.value[asd.frequencies.value <= 100][peaks]):
                    prominence = properties["prominences"][h]
                    y_text = asd_smooth[asd.frequencies.value <= 100][peaks][h]
                    
                    axes[i, j].axvline(x=frequency, color='r', linestyle='--', linewidth=0.8, alpha=0.8)
                    axes[i, j].text(
                        frequency * 1.1,     
                        y_text,
                        f"f = {frequency:.2f} Hz",
                        fontsize=9,
                        color='r',
                        va='center',
                        rotation=0)
                axes[i, j].set_title(names_list[i*3+j])
                axes[i, j].grid(True, which="both")
                print("Peak frequencies (Hz) of the derivated data:", np.array2string(asd.frequencies.value[peaks], separator=", "))
                print("Prominences (strengths of the associated peaks):", np.array2string(properties["prominences"], separator=", "))
                print()


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/single_ellipse_HoQI_ASD_plot.png")
        plt.close()

        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd = get_asd(single_ellipse_DOF_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_smooth = np.convolve(asd.value, np.ones(window)/window, mode='same')
                peaks, properties = find_peaks(np.log10(asd.value[asd.frequencies.value <= 100]), prominence=1.5)

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd.frequencies.value, asd_smooth)
                axes[i, j].plot(asd.frequencies.value[asd.frequencies.value <= 100][peaks], asd_smooth[asd.frequencies.value <= 100][peaks], "rv") # de rode markeringen moeten wel netjes op de 'gesmoothede' functie vallen
                for h, frequency in enumerate(asd.frequencies.value[asd.frequencies.value <= 100][peaks]):
                    prominence = properties["prominences"][h]
                    y_text = asd_smooth[asd.frequencies.value <= 100][peaks][h]
                    
                    axes[i, j].axvline(x=frequency, color='r', linestyle='--', linewidth=0.8, alpha=0.8)
                    axes[i, j].text(
                        frequency * 1.1,     
                        y_text,
                        f"f = {frequency:.2f} Hz",
                        fontsize=9,
                        color='r',
                        va='center',
                        rotation=0)
                axes[i, j].set_title(names_list_DOF[i*3+j])
                axes[i, j].grid(True, which="both")
                print("Peak frequencies (Hz) of the derivated data:", np.array2string(asd.frequencies.value[peaks], separator=", "))
                print("Prominences (strengths of the associated peaks):", np.array2string(properties["prominences"], separator=", "))
                print()


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/single_ellipse_data_DOF_ASD_plot.png")
        plt.close()

    if choices_dict["window_ellipse_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd = get_asd(windowed_ellipse_HoQI_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_smooth = np.convolve(asd.value, np.ones(window)/window, mode='same')
                peaks, properties = find_peaks(np.log10(asd.value[asd.frequencies.value <= 100]), prominence=1.5)

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd.frequencies.value, asd_smooth)
                axes[i, j].plot(asd.frequencies.value[asd.frequencies.value <= 100][peaks], asd_smooth[asd.frequencies.value <= 100][peaks], "rv") # de rode markeringen moeten wel netjes op de 'gesmoothede' functie vallen
                for h, frequency in enumerate(asd.frequencies.value[asd.frequencies.value <= 100][peaks]):
                    prominence = properties["prominences"][h]
                    y_text = asd_smooth[asd.frequencies.value <= 100][peaks][h]
                    
                    axes[i, j].axvline(x=frequency, color='r', linestyle='--', linewidth=0.8, alpha=0.8)
                    axes[i, j].text(
                        frequency * 1.1,     
                        y_text,
                        f"f = {frequency:.2f} Hz",
                        fontsize=9,
                        color='r',
                        va='center',
                        rotation=0)
                axes[i, j].set_title(names_list[i*3+j])
                axes[i, j].grid(True, which="both")
                print("Peak frequencies (Hz) of the derivated data:", np.array2string(asd.frequencies.value[peaks], separator=", "))
                print("Prominences (strengths of the associated peaks):", np.array2string(properties["prominences"], separator=", "))
                print()


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/windowed_ellipse_HoQI_ASD_plot.png")
        plt.close()

        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd = get_asd(windowed_ellipse_DOF_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_smooth = np.convolve(asd.value, np.ones(window)/window, mode='same')
                peaks, properties = find_peaks(np.log10(asd.value[asd.frequencies.value <= 100]), prominence=1.5)

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd.frequencies.value, asd_smooth)
                axes[i, j].plot(asd.frequencies.value[asd.frequencies.value <= 100][peaks], asd_smooth[asd.frequencies.value <= 100][peaks], "rv") # de rode markeringen moeten wel netjes op de 'gesmoothede' functie vallen
                for h, frequency in enumerate(asd.frequencies.value[asd.frequencies.value <= 100][peaks]):
                    prominence = properties["prominences"][h]
                    y_text = asd_smooth[asd.frequencies.value <= 100][peaks][h]
                    
                    axes[i, j].axvline(x=frequency, color='r', linestyle='--', linewidth=0.8, alpha=0.8)
                    axes[i, j].text(
                        frequency * 1.1,     
                        y_text,
                        f"f = {frequency:.2f} Hz",
                        fontsize=9,
                        color='r',
                        va='center',
                        rotation=0)
                axes[i, j].set_title(names_list_DOF[i*3+j])
                axes[i, j].grid(True, which="both")
                print("Peak frequencies (Hz) of the derivated data:", np.array2string(asd.frequencies.value[peaks], separator=", "))
                print("Prominences (strengths of the associated peaks):", np.array2string(properties["prominences"], separator=", "))
                print()


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/windowed_ellipse_data_DOF_ASD_plot.png")
        plt.close()

    if choices_dict["raw_data"] == True and choices_dict["single_ellipse_data"] == True and choices_dict["window_ellipse_data"] == True:
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd_raw = get_asd(raw_HoQI_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_raw_smooth = np.convolve(asd_raw.value, np.ones(window)/window, mode='same')
                asd_single = get_asd(single_ellipse_HoQI_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_single_smooth = np.convolve(asd_single.value, np.ones(window)/window, mode='same')
                asd_windowed = get_asd(windowed_ellipse_HoQI_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_windowed_smooth = np.convolve(asd_windowed.value, np.ones(window)/window, mode='same')

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd_raw.frequencies.value, asd_raw_smooth, 'r')
                axes[i, j].loglog(asd_single.frequencies.value, asd_single_smooth, 'b')
                axes[i, j].loglog(asd_windowed.frequencies.value, asd_windowed_smooth, 'g')
                axes[i, j].set_title(names_list[i*3+j])
                axes[i, j].grid(True, which="both")


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/all_three_HoQI_ASD_plot.png")
        plt.close()

        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3):
                asd_raw = get_asd(raw_DOF_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_raw_smooth = np.convolve(asd_raw.value, np.ones(window)/window, mode='same')
                asd_single = get_asd(single_ellipse_DOF_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_single_smooth = np.convolve(asd_single.value, np.ones(window)/window, mode='same')
                asd_windowed = get_asd(windowed_ellipse_DOF_displacement[i*3+j, :], fs_set, segment_time_set)
                asd_windowed_smooth = np.convolve(asd_windowed.value, np.ones(window)/window, mode='same')

                axes[i, j].set_ylabel('Gain')
                axes[i, j].set_xlabel('Frequency (Hz)')
                axes[i, j].loglog(asd_raw.frequencies.value, asd_raw_smooth, 'r')
                axes[i, j].loglog(asd_single.frequencies.value, asd_single_smooth, 'b')
                axes[i, j].loglog(asd_windowed.frequencies.value, asd_windowed_smooth, 'g')
                axes[i, j].set_title(names_list_DOF[i*3+j])
                axes[i, j].grid(True, which="both")


        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig("End_Product_Code/Plot_files/all_three_DOF_ASD_plot.png")
        plt.close()
    

## Parameter Timeseries
if choices_dict["ellipse_params_timeseries"] == True:
    HoQI_ellipse_parameter_list = [np.load('End_Product_Code/HoQI_1x_ellipse_parameter_timeseries.npy'), np.load('End_Product_Code/HoQI_2x_ellipse_parameter_timeseries.npy'), np.load('End_Product_Code/HoQI_3x_ellipse_parameter_timeseries.npy'), np.load('End_Product_Code/HoQI_1z_ellipse_parameter_timeseries.npy'), np.load('End_Product_Code/HoQI_2z_ellipse_parameter_timeseries.npy'), np.load('End_Product_Code/HoQI_3z_ellipse_parameter_timeseries.npy')]

    HoQI_names = ["1x", "2x", "3x", "1z", "2z", "3z"]
    names_list = ["x0", "y0", "a", "b", "theta", "area"]

    for h in range(0,6):
        figure, axes = plt.subplots(2, 3)
        for i in range(0,2):
            for j in range(0,3 - i):
                time = np.array(list(range(0, len(HoQI_ellipse_parameter_list[h][:, i*3+j]))))
                axes[i, j].set_ylabel('Displacement (um)')
                axes[i, j].set_xlabel('Time (ms)')
                axes[i, j].plot(time, HoQI_ellipse_parameter_list[h][:, i*3+j], ',')
                axes[i, j].set_title(names_list[i*3+j])

        plt.subplots_adjust(hspace=0.312)
        figure.set_figheight(8)
        figure.set_figwidth(16)
        figure.savefig( f'End_Product_Code/Plot_files/parameter_timeseries_HoQI_{HoQI_names[h]}.png' )
        plt.close()
    
## Velocity Data plots
if choices_dict["velocity_data"] == True:
    if choices_dict["raw_data"] == True:
        raw_HoQI_velocity = np.load('End_Product_Code/raw_HoQI_velocity_data.npy')
        raw_DOF_velocity = np.load('End_Product_Code/raw_DOF_velocity_data.npy')
    if choices_dict["single_ellipse_data"] == True:
        single_ellipse_HoQI_velocity = np.load('End_Product_Code/single_ellipse_HoQI_velocity_data.npy')
        single_ellipse_DOF_velocity = np.load('End_Product_Code/single_ellipse_DOF_velocity_data.npy')
    if choices_dict["window_ellipse_data"] == True:
        windowed_ellipse_HoQI_velocity = np.load('End_Product_Code/windowed_ellipse_HoQI_velocity_data.npy')
        windowed_ellipse_DOF_velocity = np.load('End_Product_Code/windowed_ellipse_DOF_velocity_data.npy')

    if choices_dict["raw_data"] == True:
        subplot_titles = ["1x", "2x", "3x", "1z", "2z", "3z"]

        fig, axes = plt.subplots(2, 3, figsize=(18, 9))
        axes = axes.flatten()

        time = np.array(range(0, len(raw_HoQI_velocity[0, :])))

        for i, title in enumerate(subplot_titles):
            axes[i].plot(time, raw_HoQI_velocity[i, :])
            axes[i].set_title(title)
            axes[i].set_xlabel("Time (s)")
            axes[i].set_ylabel(r"Velocity ($\mu$m/s)")

        fig.suptitle("Time series of raw HoQI velocities")
        plt.tight_layout()
        fig.savefig('End_Product_Code/Plot_files/raw_HoQI_velocity_timeseries.png')
        plt.close()

        subplot_titles = ["x", "y", "z", "Rx", "Ry", "Rz"]

        fig, axes = plt.subplots(2, 3, figsize=(18, 9))
        axes = axes.flatten()

        time = np.array(range(0, len(raw_DOF_velocity[0, :])))

        for i, title in enumerate(subplot_titles):
            axes[i].plot(time, raw_DOF_velocity[i, :])
            axes[i].set_title(title)
            axes[i].set_xlabel("Time (s)")
            axes[i].set_ylabel(r"Velocity ($\mu$m/s)")

        fig.suptitle("Time series of raw DOF velocities")
        plt.tight_layout()
        fig.savefig('End_Product_Code/Plot_files/raw_DOF_velocity_timeseries.png')
        plt.close()
    
    if choices_dict["single_ellipse_data"] == True:
        subplot_titles = ["1x", "2x", "3x", "1z", "2z", "3z"]

        fig, axes = plt.subplots(2, 3, figsize=(18, 9))
        axes = axes.flatten()

        time = np.array(range(0, len(single_ellipse_HoQI_velocity[0, :])))

        for i, title in enumerate(subplot_titles):
            axes[i].plot(time, single_ellipse_HoQI_velocity[i, :])
            axes[i].set_title(title)
            axes[i].set_xlabel("Time (s)")
            axes[i].set_ylabel(r"Velocity ($\mu$m/s)")

        fig.suptitle("Time series of single_ellipse HoQI velocities")
        plt.tight_layout()
        fig.savefig('End_Product_Code/Plot_files/single_ellipse_HoQI_velocity_timeseries.png')
        plt.close()

        subplot_titles = ["x", "y", "z", "Rx", "Ry", "Rz"]

        fig, axes = plt.subplots(2, 3, figsize=(18, 9))
        axes = axes.flatten()

        time = np.array(range(0, len(single_ellipse_DOF_velocity[0, :])))

        for i, title in enumerate(subplot_titles):
            axes[i].plot(time, single_ellipse_DOF_velocity[i, :])
            axes[i].set_title(title)
            axes[i].set_xlabel("Time (s)")
            axes[i].set_ylabel(r"Velocity ($\mu$m/s)")

        fig.suptitle("Time series of single_ellipse DOF velocities")
        plt.tight_layout()
        fig.savefig('End_Product_Code/Plot_files/single_ellipse_DOF_velocity_timeseries.png')
        plt.close()
    
    if choices_dict["window_ellipse_data"] == True:
        subplot_titles = ["1x", "2x", "3x", "1z", "2z", "3z"]

        fig, axes = plt.subplots(2, 3, figsize=(18, 9))
        axes = axes.flatten()

        time = np.array(range(0, len(windowed_ellipse_HoQI_velocity[0, :])))

        for i, title in enumerate(subplot_titles):
            axes[i].plot(time, windowed_ellipse_HoQI_velocity[i, :])
            axes[i].set_title(title)
            axes[i].set_xlabel("Time (s)")
            axes[i].set_ylabel(r"Velocity ($\mu$m/s)")

        fig.suptitle("Time series of windowed_ellipse HoQI velocities")
        plt.tight_layout()
        fig.savefig('End_Product_Code/Plot_files/windowed_ellipse_HoQI_velocity_timeseries.png')
        plt.close()

        subplot_titles = ["x", "y", "z", "Rx", "Ry", "Rz"]

        fig, axes = plt.subplots(2, 3, figsize=(18, 9))
        axes = axes.flatten()

        time = np.array(range(0, len(windowed_ellipse_DOF_velocity[0, :])))

        for i, title in enumerate(subplot_titles):
            axes[i].plot(time, windowed_ellipse_DOF_velocity[i, :])
            axes[i].set_title(title)
            axes[i].set_xlabel("Time (s)")
            axes[i].set_ylabel(r"Velocity ($\mu$m/s)")

        fig.suptitle("Time series of windowed_ellipse DOF velocities")
        plt.tight_layout()
        fig.savefig('End_Product_Code/Plot_files/windowed_ellipse_DOF_velocity_timeseries.png')
        plt.close()
    